name: Run tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  
jobs:
  run:
    uses: moosetechnology/.github/.github/workflows/run-tests.yml@main
    with:
      create-artifact: ${{ github.event_name == 'push' }} #Create artifact only after a push
      image-name: MooseIDE
